global:
    scrape_interval: 15s
    external_labels:
        monitor: 'demo-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'api_monitor'
    static_configs:
      - targets: ['flask:9200']
  
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']

